In [1]:
import numpy as np
a = np.array([5,5,5,5])
a

array([5, 5, 5, 5])

In [2]:
import numpy as np
a= np.array([5,5,5,])
a


array([5, 5, 5])

In [3]:
type(a)

numpy.ndarray

In [9]:
# list of lists
import numpy as np
b = np.array([[5,5,5], [5,5,5], [5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

Vector and matrix.  
vector is and array and single dimention with no difference of row and column.
matrix. refers to array with two dementions. 


In [12]:
import numpy as np
a=np.array([5,5,5])
a

array([5, 5, 5])

In [13]:
type(a)

numpy.ndarray

In [17]:
len(a)

3

In [18]:
a[0]

np.int64(5)

In [19]:
a[0:]

array([5, 5, 5])

In [20]:
# list of lists
b = np.array([[5,5,5], [5,5,5], [5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [21]:
type(b)

numpy.ndarray

In [23]:
len(b)

3

In [24]:
b[0]

array([5, 5, 5])

In [25]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [28]:
c = np.array([[5,5,5], [5,5,5]])
c

array([[5, 5, 5],
       [5, 5, 5]])

In [29]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [30]:
b = np.zeros(2)
b

array([0., 0.])

In [31]:
c = np.ones(3)
c

array([1., 1., 1.])

In [32]:
# create an empty arraywith 2 elements
d = np.empty(3)
d

array([1., 1., 1.])

In [33]:
# with range of eleetns
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [34]:
# with specific range of elements
f = np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [35]:
# continue
g = np.arange(2,30,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [39]:
# linerly spaced arrays
h = np.linspace(0,10,num=5)  # gives use of 5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [40]:
# specific dat types
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [41]:
j = np.ones(3, dtype=np.float64)
j

array([1., 1., 1.])

In [42]:
# making and reshaping a 3D array
c = np.arange(24). reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])